language: node_js
node_js:
- node
deploy:
  provider: npm
  email: igorify@gmail.com
  api_key:
    secure: B+4SxqsSOb2yVMWAjZ7irHLL9WSrUWKGw+6pn2iu/rfBBO1qVh3CaWtnqncoc1qAYYIqaskpt8AWbJoq5TVMJaXJFspFZlN6x59djUa3BbzoKkD/QcQwTiMMIuquuPcgvXELv4yWh0485S1C/8qgAGcqfZx3ZmIGy3OCB0UN9dsG9+TEwzwTpIQga/CzY4PKDFS9cDRP/h995o1ph+OAshG2S7bxjm59x4JiNWamMksTYgG5iEJ0XXxoqaSk7gbV47E0X8iDdAuDwZ5/XwX5ltH4HK/7sPTqJtG0ecmg4wk1iEGAwjsTzTPpFnfvxNFt0BCcFtMjDXZqvEu96jHM+ldlpiv0/YZPc31BMv9Mg8DNmm4msVNifeiLT/a//pBAP9Im6yB65YfT8HB+RC+U3DDxlwCpayEi3sLdKklmxIKakSeE7rIzW6p3YypLv/OQo+RNAHfXw2nYzi1Ww0ZO3InCUkow71iH+x7UFFsXzPZWc/PkR7UsybqFiuz6T9c8Dmnq97JbSLGZCea69oJMJwT/yt98wu1iZ8fhOerMhcV3qKdPTyIADYqsbf5RNojIMVEixbHka8uWaCjZbDurpNj5o1ejRZGZh5OSp0cgX7bU1ax+sVtCWLTZ1qJj4MxiBKlisGMDfovmK0FWGws278ANB8rSW+ya2DQO4yt+6Qc=
  on:
    tags: true
    repo: igorify/getthemall
